### ISSUE TITLE
Pre-defined list of links

### ISSUE THREAD

**Issue by sezdec** [Adam-it/TilesLinksForSPOnline#12]
Awesome solution! The option for an admin to create a pre-defined list of organization links that a user can add or remove is a great idea.

**Comment by Adam-it** [comment]
wow thanks 😊. I don't have much time but the admin options is something I will for sure include later on. Currently I am working on SP Extensions that may be added to any list or lib or site (in top bar). Te extensions will be buttons which will allow to add a link to the selected item, document or current page. So the user will be able to add a link (tile) from anywhere in SharePoint.

**Comment by sezdec** [comment]
Sounds great!

**Comment by Adam-it** [comment]
reopening this as issue as now I finished the extensions to add tiles from any page or for any item and the last fixes to show error message when permissions were not approved and now I will focus my time on a feature which will allow the organization to set in a dynamic way some predefined list of links (tiles) the user will be not able to remove or edit (besides changing the tile position)

**Comment by shb2002** [comment]
Any update on this feature? I'm pretty keen on this one, selecting from pre-defined list.

**Comment by Adam-it** [comment]
> Any update on this feature? I'm pretty keen on this one, selecting from pre-defined list.

Thanks for reaching out 👍. 
TBH I didn't actually think anyone was interested in this solution and I was even thinking to move it to PnP webpart sample repo as a new way to present favorite sites 🤔.
At the moment I have a script that will setup an admin site with the list where admins could add predefine links for all users in the tenant. Check branch ->https://github.com/Adam-it/TilesLinksForSPOnline/tree/adminPredefinedList/AdminSite
So the only feature left it to modify the webpart to present those links as not editable/deletable tiles🤔.
TBH at the moment I wasn't planning any time to work on this. I think I should find some time to finish this maybe around Christmas 👍

**Comment by shb2002** [comment]
That will be awesome :+1:
The way I was thinking was that (end) users see an edit icon next to the link tiles. They click on it, then a panel opens showing the list of predefined links which they can drag-n-drop to another section in the same panel. They can also rearrange the selected links in the same panel. This can be presented simply as two lists in the panel, if not tiles. Once they are done, they click on "Save" button on the panel. The panel goes away and the updates reflects on the page for the user.

**Comment by Adam-it** [comment]
added functionality:
👉please see new part of README in webpart https://github.com/Adam-it/TilesLinksForSPOnline/blob/master/Webpart/README.md#predefined-links-optional-setting
👉and how to setup Admin Site https://github.com/Adam-it/TilesLinksForSPOnline/tree/master/AdminSite

closing the issue
