### ISSUE TITLE
Spinner remains in 'Loading ...' state, and links disappearing after page refresh

### ISSUE THREAD

**Issue by sezdec** [Adam-it/TilesLinksForSPOnline#14]
Hi

After deploying the webpart to SharePoint Online, I experienced two issues:

1. The Spinner and ' 'Loading ...' message remains visible at all times.
2. I can add and save personal links, but the links disappear once the page refreshes 

If there's other info I can provide to help troubleshoot please let me know.

**Screenshots**

<img width="319" alt="personallinksloading" src="https://user-images.githubusercontent.com/20509818/109920749-dadf1800-7d0e-11eb-8f31-423337193972.PNG">

**Comment by Adam-it** [comment]
hi,
sorry for the bad start 😊. I think you are lacking some permissions to graph API as the webpart is using it. All the data used in the webpart (so the links)  are being saved on user OneDrive (that way use has the same data (links/tiles) between SharePoint and Teams). The folder keeping the data should be created on the first startup of the webpart in your onedrive in the Apps folder. Should look something like this:
![image](https://user-images.githubusercontent.com/58668583/109965541-6183fd00-7cef-11eb-8b37-8f0a2c3872f0.png)
Could you check if such a file is present in your OneDrive 🤔? 
in the mean time I will 
- [ ] try to reproduce the first start up of the webpart (I didn't do it for a long time, maybe I added some feature that broke it 🤔)
- [ ] investigate this permissions to graph API

**Comment by Adam-it** [comment]
ok I think I managed to reproduce it a bit. I mean I had the same problem visible loader at first start even if I added some tile. But then when I refreshed the page the links loaded normally (the loader hides) and the data is present in the app location in OneDrive. Did you experience something similar? 
The below link is a movie how it worked on my side when I tried to reproduce your error. (sorry for the mix of english and polish language on the sites ... I was in a hurry 😋)
https://user-images.githubusercontent.com/58668583/109967769-1fa88600-7cf2-11eb-9bd4-bec0d2a1773d.mp4

**Comment by Adam-it** [comment]
ok regarding the permissions I also checked this and I have a question:
after you deployed the app did you go to the API management screen and checked all pending approval API permissions? As this webpart is using Graph API the tenant admin has full control of permissions he or she grants. Maybe those are still unchecked and that is why the webpart is unable to save any data on you OneDrive. 
To get more detail of the thing I am referring to please check this part of [MSD documentation - deploy the solution and grant permissions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#deploy-the-solution-and-grant-permissions) ... I think this might be it 🤔

**Comment by sezdec** [comment]
Thank you for investigating, and for your advice. I don't have anything in my OneDrive, so it seems you are right about the API permissions.

I don't have any pending API approvals, but can you confirm which permissions I need to grant (e.g. Tasks.ReadWrite)? Maybe the webpart hasn't built correctly for me.

**Comment by Adam-it** [comment]
ok .. thanks for checking. 
I noticed the app is missing the permissions request in manifest.. I will update it (it is a quick fix) and will let you know when it's ready

**Comment by Adam-it** [comment]
ok I added a fix and checked on a clear tenant... should work 😉. Please download latest code, rebuild, redeploy... after that you should see permission request in the API management site. After approving it the webpart should work the same as presented on the movie couple of comments above 😊.
If the problem is still not resolved after the last fix please reopen this issue so I will investigate more.
Anyway thanks a lot for checking the webpart and for the feedback. I think after that I will include the fallowing to my solution to make it more user friendly 😉
- the webpart loader is not hidden on first use after adding first tile (when the json data file i still not present)
- webpart should show some error message that the user did not approve the needed Graph API permissions

**Comment by sezdec** [comment]
All working as expected with the latest code - thanks again!

**Comment by Adam-it** [comment]
Cool. Thanks again for your feedback.
