### ISSUE TITLE
Style suggestion

### ISSUE THREAD

**Issue by sezdec** [Adam-it/TilesLinksForSPOnline#18]
Keep up the awesome work!

Just a suggestion - can the layout of the fluent ui icons and font be changed to match the default SharePoint Online layout and font? This will give your webpart a consistent look with other SharePoint Online webparts. I've attached an example from your webpart, and one that uses the default SharePoint layout and font. 

TilesLinksForSPOnline: 
<img width="111" alt="TilesLinksForSPOnline example" src="https://user-images.githubusercontent.com/20509818/110400590-01fd6700-80cc-11eb-85df-471daa6d8e14.PNG">

Default SharePoint:
<img width="102" alt="Default SPO example" src="https://user-images.githubusercontent.com/20509818/110400600-0590ee00-80cc-11eb-91d0-559e575b0ae5.PNG">

**Comment by Adam-it** [comment]
Good comment... For sure looks better. I will reopen this and add this in some coming PR.

**Comment by sezdec** [comment]
Thanks Adam.

**Comment by Adam-it** [comment]
ok.. seems to be better after latest changes 
![image](https://user-images.githubusercontent.com/58668583/111043680-0f0bb480-8444-11eb-939c-c1fdfdc53531.png)
