### ISSUE TITLE
[🐞 Bug] Web part is not working for adding new tiles

### ISSUE THREAD

**Issue by ZzyzxIsAlreadyTaken** [Adam-it/TilesLinksForSPOnline#23]
**Describe the bug**
Add new tile button does not work

**To Reproduce**
1. Build the webpart
2. Upload and enable app package in App Catalog
3. Authorize use of API to access OneDrive (I guess)
4. Click on Add new tile in added web part in a page
5. See error

**Expected behavior**
I have not made the changes to create an admin site so that error is expected. 
But beeing able to manage personal links should work without that step? 
Nothing happens except trigging an error in console happens whenclicking on "Add new tile"

**Screenshots**
Screenshot of error in console:
![image](https://user-images.githubusercontent.com/18461079/205633570-31f3bfea-74a2-4999-a532-f7ad729412f2.png)

**Comment by Adam-it** [comment]
hi @ZzyzxIsAlreadyTaken Thanks for adding the bug 👍
TBH it's been a while since I used/developed this solution and actually on some level I moved it as a new sample in PnP Webpart repo as a [view for followed sites](https://dev.azure.com/PG-TR/SpecTra/_apps/hub/ms-devlabs.team-retrospectives.home) and I thought I archived this repo 😅.
But anyway I will give it a check in the coming weekend and let you know of the results.  If I remember well the webpart should work without the admin part but I might be wrong 😉.

**Comment by icusick** [comment]
hi, @Adam-it and @ZzyzxIsAlreadyTaken . i hope it's okay for me to comment here. i was reading this issue to see if could help me resolve a different problem i was having and i noticed that in the screenshot shared by @ZzyzxIsAlreadyTaken , the endpoint is pointing to "https://sample.sharepoint.com/sites/PersonalLinksAdminSite". @ZzyzxIsAlreadyTaken you need to update "sample" to your domain and then also make sure that there is a site at the URL PersonalLinksAdminSite. right now, you're sending an api request to a place that doesn't exist. so update the string in the GlobalSettings.ts file to your sharepoint domain and then it might work.

**Comment by Adam-it** [comment]
Very good comment.
Thanks @icusick for your help 👍. You rock 🤩.
@ZzyzxIsAlreadyTaken could you give it a check?

**Comment by Adam-it** [comment]
@ZzyzxIsAlreadyTaken if you created the list manually not via script then most probably you have different internal names of columns than the one generated by script.
you need to again update the [GlobalSettings.ts](https://github.com/Adam-it/TilesLinksForSPOnline/blob/master/Webpart/src/webparts/personalTiles/globals/GlobalSettings.ts) 
Updating the LinkName and LinkUrl column internal names to your internal names
![image](https://user-images.githubusercontent.com/58668583/206204492-65f1d8f8-0141-4910-8cef-5c30cd0a0fe0.png)
You may get the internal name of the column when you add sorting on the list and take the internal name of the sorted column from the url like
![image](https://user-images.githubusercontent.com/58668583/206204676-57847676-167d-444a-bdcc-a7b4121ed335.png)

BTW I need to remove the console log from that part you printed 😉

Give it a try and let me know if it helped 👍

**Comment by ZzyzxIsAlreadyTaken** [comment]
You have upgraded your webpart to new version of SPFx? 

I have updated the internal names of the columns and yes, it seems to work now. :) Somehow all the internal names are missing spaces. Have MS done something about how list columns internal names are created? 

Found another **bug** though, and have a **question**. 

**Q:** How do you handle icons from the predefined personal links?

**Bug:**  The web part lets me try to set icons for predefined links, but it obiously does not work as it then would have to write back to the admin list and that would set the icon for everyone. :)

**Comment by Adam-it** [comment]
> You have upgraded your webpart to new version of SPFx? 

No not yet, this PR is still draft and I still need to upgrade the extension. The web part is ready, but still not merged.


> I have updated the internal names of the columns and yes, it seems to work now. :) Somehow all the internal names are missing spaces. Have MS done something about how list columns internal names are created? 

I think it was corrected when creating from UI. The behavior didn't change when using the script. It's good it is working now.

> Found another **bug** though, and have a **question**. 
> 
> **Q:** How do you handle icons from the predefined personal links?

There is no support in it. if I remember well you just need to specify the icon class name but I will double check and let you know. 

> **Bug:**  The web part lets me try to set icons for predefined links, but it obiously does not work as it then would have to write back to the admin list and that would set the icon for everyone. :) 

Good catch. Do you think you could open a separate issue to track this? I would rather not extend the scope of the current one.

**Comment by Adam-it** [comment]
@ZzyzxIsAlreadyTaken yes I remembered correctly. In the predefined personal links in the icon column you only need to specify the icon class name.
Currently the webpart supports the official MS Fluent UI icons
https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

There is no visual support in picking the icon in the admin list. You may find the class name from the above link and just put the correct one. Then when a user will select this predefined link to create a new personal link then he or she will get a new link with the correct icon

![image](https://user-images.githubusercontent.com/58668583/208770583-a847a4d8-bf37-486e-bb98-c7ef07ce804b.png)

**Comment by Adam-it** [comment]
@ZzyzxIsAlreadyTaken I made latest update to this solution making the predefined links as optional by default which will resolve this problem.
Along the way the solution was updated to latest version of SPFx (currently 1.16.1) which I would recommend to use as in the near future it will allow to use this webpart also in Outlook and Offcie.com site (currently this is still in preview so the webpart may only be used in SharePoint and Teams but this functionallity will be GA this year 🤩)
